FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y apt-transport-https
# RUN apt-get upgrade
RUN apt install -y python3
RUN apt install -y python3-dev   
RUN apt install -y python3-pip    
RUN apt install -y python3-opencv   
RUN apt install -y vim-tiny  
RUN pip3 install numpy paho-mqtt
WORKDIR /apps
COPY client.py client.py
COPY haarcascade_frontalface_default.xml haarcascade_frontalface_default.xml
#CMD python3 /apps/client.py
