FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt install -y python3-dev python3-pip vim-tiny
RUN pip3 install numpy paho-mqtt
WORKDIR /apps
COPY server.py server.py
#CMD python3 /apps/server.py

